version: '3.7'

services:
  spielerplus-calendar:
    image: djbrown/spielerplus-calendar:latest
    container_name: spielerplus-calendar
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./config.json:/app/config.json:ro
  spielerplus-calendar-wrapper:
    image: odin568/spielerplus-calendar-wrapper:latest
    container_name: spielerplus-calendar-wrapper
    restart: always
    depends_on:
      - spielerplus-calendar
    ports:
      - "5000:8080"
